Feat/modify auth
bitcomputing/go-reddit pull request #1
Opened 2024-10-29 09:01 UTC by joglea

2024-10-29 09:48 UTC, soasurs requested changes

2024-10-29 09:48 UTC, soasurs commented on reddit/reddit.go
> +func (c *Client) Do(ctx context.Context, req *http.Request, v interface{}, isJob bool) (*Response, error) {
`isJob` 这个参数在初始化 Client 的时候就可以确定吧，不会在同步和异步之间切换的。

2024-10-29 09:48 UTC, soasurs commented on reddit/reddit.go
> +	BearerToken string
这两个 token 应该就是同一个吧？

2024-10-29 09:48 UTC, soasurs commented on reddit/reddit.go
> +
可以参考上面的写成 ```WithXXX` 形式。

2024-10-30 02:58 UTC, joglea commented on reddit/reddit.go
> +	BearerToken string
不是，accesstoken是到时候reddit服务里调reditt api用的，bearertoken是workflow那边调proxy服务传的proxy_api_key

2024-10-30 02:59 UTC, joglea commented on reddit/reddit.go
> +
oauthTransport这个是他原始仓库里的方法，就没动

2024-10-30 03:05 UTC, joglea commented on reddit/reddit.go
> +func (c *Client) Do(ctx context.Context, req *http.Request, v interface{}, isJob bool) (*Response, error) {
如果是从初始化的Client里传过来的话  比如comment.go里的Submit和SubmitAsync就不需要分开写两个方法了

2024-10-30 03:52 UTC, soasurs commented on reddit/reddit.go
> +	BearerToken string
这两个 token 最终的使用方法都是在 request header 的 Authorization 里写 `Bearer <token>` 吧，感觉一个字段就够了。

2024-10-30 03:52 UTC, soasurs commented on reddit/reddit.go
> +func (c *Client) Do(ctx context.Context, req *http.Request, v interface{}, isJob bool) (*Response, error) {
嗯，初始化的时候指定就行了，中间肯定是不会切换的。

2024-10-30 08:17 UTC, joglea commented on reddit/reddit.go
> +	BearerToken string
本质上都是Authorization 里写 Bearer <token>，但走了两条不同的路，，workflow那边走proxy调用的时候是走我直接加的authorizationTransport，reddit服务里是走原项目里封装的oauthTransport，里面过了oauth2这个包的实现

2024-10-30 08:19 UTC, soasurs commented on reddit/reddit.go
> +	BearerToken string
> 本质上都是Authorization 里写 Bearer ，但走了两条不同的路，，workflow那边走proxy调用的时候是走我直接加的authorizationTransport，reddit服务里是走原项目里封装的oauthTransport，里面过了oauth2这个包的实现

他用 oauth2 那个包是为了自动刷新 token 吧，我们每次都是拿 token 然后设置，应该用不带上 oauth2 那个 package 的功能了。

2024-10-30 08:41 UTC, joglea commented on reddit/reddit.go
> +func (c *Client) Do(ctx context.Context, req *http.Request, v interface{}, isJob bool) (*Response, error) {
把isJob参数去掉了，在Client里加了个isSync用来标记

2024-10-30 08:45 UTC, joglea commented on reddit/reddit.go
> +	BearerToken string
那我把access_token这个去掉好了 ,统一走InitializeBearerToken，差别就是reddit服务自己调的时候要InitializeUserAgent，workflow那边就不用InitializeUserAgent，

2024-10-30 09:00 UTC, soasurs commented on reddit/reddit.go
> +	BearerToken string
感觉还是每次创建新的 Client 吧，复用 Client 感觉会有问题，我想到场景是如果后面一个 Pod 里要消费多个 client_id 的 App 的时候得加锁，感觉没必要。

2024-10-30 09:42 UTC, merged